file:
  upload-dir: upload
codigos:
  codigo-validador: "65f20d4e340a2d1109f3ba79"
  codigo-gerador: "65f20d4e340a2d1109f3ba79"
  limite-acesso: 20
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20GB
      max-request-size: 21GB
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
    deserialization:
      fail-on-unknown-properties: false
    time-zone: "America/Sao_Paulo"
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/library}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:12345}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  packagesToScan: org.astaron.bibliotecalogica.controller
  swagger-ui:
    path: /docs-library.html
  api-docs:
    path: /docs-library