package org.astaron.bibliotecalogica.model;

public enum CategoriaEnum {
	OCULTISMO,
	HISTORIA,
	ALQUIMIA,
	ALTA_MAGIA,
	ASTROLOGIA,
	BRUXARIA,
	CHAKRAS,
	CURA,
	DEFESA_PSIQUICA,
	FEITICOS,
	MAGIA_ANGELICAL,
	MAGIA_DO_CAOS,
	MAGIA_DRACONIANA,
	MAGIA_ONIRICA,
	MAGIA_SEXUAL,
	WICCA,
	XAMANISMO
}
