name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12345
          MONGO_INITDB_DATABASE: library
        # Removendo a opção options para simplificar e ver se resolve o problema de inicialização.

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag biblioteca-logica:latest

      - name: Run container from the image
        run: |
          docker run --name app -d biblioteca-logica:latest
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:latest
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            docker tag ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:latest ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:$TAG
            docker push ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:$TAG
          else
            docker push ${{ secrets.DOCKER_USERNAME }}/biblioteca-logica:latest
          fi
