name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12345
          MONGO_INITDB_DATABASE: library
        # Removendo a opção options para simplificar e ver se resolve o problema de inicialização.

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag biblioteca-logica:latest

    - name: Run container from the image
      run: |
        docker run --name app -d biblioteca-logica:latest
